name: Build and Publish

on: [push, workflow_dispatch]

jobs:
  build-publish:
    permissions:
      contents: read
      id-token: write
    uses: viamedici-spc/github-ci/.github/workflows/build-npm.yml@v3
    with:
      node-version: '24'
      build-verbs: 'build,test'
      skip-publish: false
